### ISSUE TITLE
how to disable input.conf override ?

### ISSUE THREAD

**Issue by spvkgn** [np1/mps-youtube#178]
mps-yt from develop branch launches mpv with ```--input-conf=/tmp/mpsyt-input``` followed by override my input.conf

Is there a way not to override it?

Thanks.

**Comment by np1** [comment]
Hi, thanks for testing the develop branch. I could add a `--no-input-override` flag to mpsyt to stop it doing this. It would then be advisable for those with a custom input.conf to map the following additional keys in their custom config;

`quit 42` for previous track
`quit` for next track
`quit 43` to exit a playing playlist

I could add an explanation of this in the wiki / faq

**Comment by ids1024** [comment]
@np1 Do you think there would be any problems with reading the user's input.conf and replacing "playlist_prev" (pt_step -1 with mplayer) with "quit 42" and "playlist_next" ("pt_step 1" with mplayer) with "quit 43" (this would mean a minor change in how the exit codes are interpreted).

This way either standard mpv/mplayer keybinds would be used, or the user's custom ones.

**Comment by np1** [comment]
I think it's a good idea. We would need to hunt around for the input.conf file (/etc/mplayer,  /usr/local/etc/mplayer, ~/.mplayer) wouldn't we?

**Comment by ids1024** [comment]
Yes, it would require finding all the paths. Do you know where the file is stored on Windows? I also don't know if Mac is different for normal Unix.

**Comment by ids1024** [comment]
Looking at mpv's code, this is what I get, in order:

- Specified at command line
- os.environ.get('MPV_HOME')
Windows (and not Cygwin)
------------------------
- os.environ['APPDATA']
- directory of mpv.exe
- directory of mpv.exe/mpv

Unix (including OSX and Cygwin)
-------------------------------
- os.environ.get('XDG_CONFIG_HOME', os.environ['HOME'] + '/.config') + '/mpv'
- os.environ.get('HOME') + '/.mpv' #Compatability with older versions
- if OSX: https://github.com/mpv-player/mpv/blob/master/osdep/path-macosx.m
- MPV_CONFDIR, which seems to be defined during compilation (could be problematic)

The manpage lists these directories, but the precedence is less clear. I haven't found the code specifying system level configuration files, but according to the manpage that would be at /usr/local/etc/mpv/, depending on --prefix during compilation.

Would it be better to just have mpsyt specific input.conf files (one for mplayer and one for mpv) that people can edit? Perhaps with the same replacement I mentioned, so that it can be just a symlink.

**Comment by np1** [comment]
Yes, I think the mpsyt specific input.conf file will be simpler to implement. I'm not sure what you mean by "it can be just a symlink", what would be symlinked?

**Comment by ids1024** [comment]
I mean that there would be an mpv-input.conf and mplayer-input.conf in ~/.config/mps-youtube, which people could edit. They could also replace mpv-input.conf with a symlink to ~/.config/input.conf. Mpsyt would then replace instances of "playlist_prev" with "exit 42".

Or, alternatively, there could be a configuration option storing the path to the input.conf to be used. If it is not set, the defaults would be used.

**Comment by np1** [comment]
See notes for integrating mpv/mplayer custom keymappings:

https://github.com/np1/mps-youtube/wiki/Troubleshooting#custom-mplayer-or-mpv-keyboard-shortcuts-are-ignored
