### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by ids1024** [np1/mps-youtube#205]
@np1 When do you plan on releasing a new version of mpsyt?  The current version is essentially unusable with recent versions of mpv on Unix systems.  Have you figured anything out about the issue you mentioned with PR #180?

**Comment by np1** [comment]
A new version should be released soon, I agree it's not good that the current release doesn't work with newer mpv releases. I don't like to set dates for this kind of stuff in case I don't manage to keep them. Hopefully I will have time to work on it this weekend. Here are some things that I would like to have done before releasing the next version:

 - Add help text for new features / config options
 - Create a separate branch for the py2exe setup.py (currently the dev setup.py produces warnings with pip)
 - Use input conf file based on whether file exists in config dir instead of by using the `set` command
   - Update faq to include notes on using a custom input conf file
 - Update whats new section
 - Fix issue with pafy (https://github.com/np1/mps-youtube/issues/197) and release new version
 - Update keyboard mapping help text (`show_mplayer_keys` option)
 - Improve `download_command` by adding substitutions for directory and filename.
    - Handle transcoding with custom `download_command`

I'm not too concerned about fixing the issue I mentioned in #180 before the next release if it only affects Windows XP although I will have another look at it.

**Comment by ids1024** [comment]
It should not be necessary to create a branch for py2exe. If nothing can be done to eliminate the warning, there can be a separate `setup-py2exe.py`.

**Comment by ids1024** [comment]
> Use input conf file based on whether file exists in config dir instead of by using the `set` command

Do you mean a file in `~/.config/mps-youtube`, or the player's own configuration file?  I presume the former.  The current method has the advantage that it can use the same configuration file the user is already using without modification or copying it to a new location.

**Comment by np1** [comment]
@ids1024 
Thanks for the setup-py2exe.py
Regarding the input config file, yes I meant a file in ~/.config/mps-youtube. I want to change it so that if a file called `mpv-input.conf` or `mplayer-input.conf` exists then that will be used. I realise the advantage of the current method although I want to try to keep the mpsyt config settings simple, I don't think it's something that would need to be changed often and I don't like that it currently has separate settings for mpv and mplayer.

**Comment by ids1024** [comment]
For the `mpv(/mplayer)-input.conf`, are you planning on removing substitution code?  If it is left, someone could use `ln -s ~/.config/mpv/input.conf ~/.config/mps-youtube/mpv-input.conf` and get the same functionality as the current setting.

**Comment by np1** [comment]
Yep I want to keep the substitutions, I'm happy with what you implemented I just don't like that it is a config setting.

**Comment by np1** [comment]
I'm thinking again that I should create a separate branch for py2exe so that we don't have to maintain two setup files.

The py2exe branch can merge changes from master branch with every release.

**Comment by ids1024** [comment]
I think using a file rather than a branch is better.  With a separate branch, you would still have to maintain two setup files, but one would just be in the `py2exe` branch.  To me it seems like a branch would make it more complicated.

**Comment by np1** [comment]
Well, currently every change I make in setup.py I will also need to make in setup_py2exe.py, for example [changing a version number](https://github.com/np1/mps-youtube/commit/7fb0b1815932d2be21ed4fc8a1b360f5c345b8fd). git merge would be able to do that for me with separate branches. The setup_py2exe branch would only be used for creating Windows builds, it's more of a dev-script and won't be so widely used so I don't see the issue with having it in another branch.

**Comment by np1** [comment]
v0.2.2 released
