### ISSUE TITLE
mps-youtube text grayed out in the Ubuntu Sound Menu

### ISSUE THREAD

**Issue by hotice** [np1/mps-youtube#261]
The mps-youtube 0.2.4 text (as well as the thumbnail) is greyed out in the Ubuntu Sound Menu. Screenshot: http://i.imgur.com/YdMVjGl.png

**Comment by hotice** [comment]
It looks like setting "CanRaise" to True and use a NotImplementedError for 'raise' fixes this issue. Here's a patch that works great for me: https://dl.dropboxusercontent.com/u/1113424/fix-grayed-out-ubuntu-sound-menu.patch

**Comment by ids1024** [comment]
I'm not sure that is a good solution. Do the controls in the sound menu work fine other than being greyed out? If so, it seems the problem is in the user interface provided by Unity's sound menu. Mpsyt cannot be raised, so setting `canRaise` to false is correct.

**Comment by hotice** [comment]
Yes the controls work. Yes, it can't be raised but it doesn't look right imho and the patch doesn't affect its functionality. But of course this is just my opinion...

**Comment by hotice** [comment]
And one more thing: it's not grayed out elsewhere, for instance, when used with GNOME Shell Media Player Indicator extension.

**Comment by hrnr** [comment]
I think this is not bug, since mps-yoube can't raise (and it really can't being a console app) the button is greyed out because it can not be clicked (as always).

Ubuntu Sound menu is just a weird thing. They use desktop file everywhere, which adds another level of complexity and as far I know it the only benefit is that small icon before player name (icons cannot be retrieved throught MPRIS). Also ubuntu sound menu was designed with destop apps in mind, therefore we have it's strange behavior with raising, desktop files etc.

So if you don't want sound menu's behavior, I'd try messing with gtk styles, to force buttons in sound menu not to be greyed out or use a different applet (probably any other applet will be fine, as I don't thing there are 2 persons on the planet thinking that mixing desktop files and MPRIS makes a good applet).

**Comment by ids1024** [comment]
My opinion is that this is the fault of the Ubuntu developers. They decided to make the text grayed out when the player is not raiseable, so I don't think mpsyt should lie about supporting that to change what they provide as a ui.
