### ISSUE TITLE
Is the slow speed a feature or a bug?

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [np1/mps-youtube#307]
So I was listening to stairway to heaven and I found this spooky voice singing the song in a very slow motion the other day.Later on, I discovered that I could manipulate this feature-or-bug thing when I pressed ctrl+PageUp or ctrl+PageDown. As you know, ctrl+PageUp and ctrl+PageDown , are the keys used to switch between terminal tabs.However, this bug only occurs when I try to accidentally press ctrl+PageUp or ctrl+PageDown when there are no other terminal tabs beside the one opened with mps-youtube on the current terminal window.

This feature-or-bug is only available in slow speed, could you please provide the pair feature-or-bug(fast speed) please.

**Comment by ids1024** [comment]
> As you know, ctrl+PageUp and ctrl+PageDown , are the keys used to switch between terminal tabs.

Actually, I don't know because I am not using the same terminal emulator as you, and mine (st) does not even have tabs. But anyway...

Whether or not it is a bug (which I doubt), it is due to mpv or mplayer rather than mpsyt. Which are you using?

Both players have keybindings for changing the speed, but it doesn't look like ctrl+PageUp/Down should do it. The `{` `}` `[` and `]` keys should change speed be default, and `backspace` should reset the speed.

**Comment by IAlwaysBeCoding** [comment]
Interesting... I honestly didn't know mps-youtube was using another program under the hood to play the music. I am using ubuntu 14.04, and to switch between tabs you use ctrl+PageUp/ctrl+PageDown with the ubuntu default terminal.

However, I dont find it a big deal though or a deal breaker, other than that your software has become an indispensable tool in my arsenal(along with coffee) to crank out code without leaving my terminal. 

I was using [pianobar](https://github.com/PromyLOPh/pianobar) for listening to pandora without ads and free through the terminal, but pandora is more like a radio.Also, I wanted something that I could use to play youtube music through the terminal and I found your magnificent piece of software that accomplishes this very well.
