### ISSUE TITLE
Decrease in Number of Supported Formats

### ISSUE THREAD

**Issue by paddatrapper** [np1/mps-youtube#315]
Tracks that used to be playable are no longer able to be played. "Sorry mplayer doesn't support this stream. Use mpv or download it"

For example: WALK THE MOON - Shut Up and Dance (Audio) was playable yesterday, but it is now no longer playable.

System details:
 1. Arch linux running Python 3.4.2
 1. mps-youtube version 0.2.5

**Comment by ids1024** [comment]
There is a bug in [pafy](https://github.com/np1/pafy) that causes the the available streams to vary, i.e. a stream that should be listed sometimes isn't. I have yet to find the cause, but I think that could be the issue.

Could you try exiting mpsyt or running `clearcache`, and then try again? If it is due to the bug I am thinking of, doing this a few times should get it to inexplicably start working.

**Comment by np1** [comment]
This error is displayed when a stream is served over https because mplayer doesn't support streaming content using https.

I encountered this issue previously and managed to tweak pafy to ensure it returned http urls

IIRC I achieved this by changing from a faked browser user-agent string to a custom user-agent string in my http requests.

Perhaps now https is being enforced for some content.

**Comment by paddatrapper** [comment]
`clearcache` and restarting did not solve the problem. Certainly in browsers YouTube is forcing https, but I'm not sure whether this is the case for mplayer

**Comment by ids1024** [comment]
Yes, it looks like youtube is forcing https. I tried that video with both https and http. The former works, while the latter returns 403 forbidden.

That said, mplayer seems to be working fine for me with https. According to [a bug report](http://trac.mplayerhq.hu/ticket/2183) in the mplayer trac, this was fixed eight mouths ago in mplayer commit r37294.

@np1 Should we remove the current code for failing on https streams in mplayer, or test the mplayer version number like the mpv code does for some things?

**Comment by ids1024** [comment]
I have written code for getting the mplayer version, but it has the same issue as mpv, dealing with both vcs versions and releases. This is more important for mplayer, since it is standard to use the svn version, and that is recommended by the developers. Luckily, svn commit numbers, unlike git, are simple sequential integers.
```python
p = subprocess.Popen(['mplayer', '--help'], stdout=subprocess.PIPE)
mplayer_help = p.communicate()[0].decode()
m = re.search('^MPlayer SVN-r([0-9]+) ', mplayer_help, re.MULTILINE)

ver = 0
if m:
    ver = m.groups()[0]
else:
    m = re.search('^MPlayer ([0-9])+.([0-9]+)', mplayer_help, re.MULTILINE)
    if m: 
        ver = m.groups()
```
I have not yet added this code to mpsyt.

**Comment by ids1024** [comment]
The above test is implemented in commit 4126439d5d0457178ddb187fd1887d32291e2081.

**Comment by paddatrapper** [comment]
How do I update to the develop branch to test this using pip?

**Comment by ids1024** [comment]
`pip3 install - U https://github.com/np1/mps-youtube/archive/develop.zip`

You need a recent mplayer build. The one in the Archlinux repos should do fine.

**Comment by paddatrapper** [comment]
Thanks. This did fix the issue

**Comment by np1** [comment]
Good job with the version test @ids1024 . I think the error message should be updated to advise using mpv or a newer version of mplayer.

**Comment by ardcore** [comment]
I'm experiencing the same issue, getting `Sorry mplayer doesn't support this stream. Use mpv or update mplayer to a newer version` message whenever I try to play an audio/video which _isn't_ .ogg.

Already went through the steps advised here (replacing the develop.zip url with the current repo's one and downloading latest mplayer snapshot from their site), but it doesn't help.

In my case, the error is also accompanied with `WARNING:root:Unknown itag: 13` as in #342, not sure if that's related.

Here are my system details:
```console
 γ ~ mplayer | grep MPlayer
MPlayer UNKNOWN-4.2.1 (C) 2000-2015 MPlayer Team
 γ ~ pip freeze | grep pafy
pafy==0.3.74
 γ ~ mpsyt -v

mpsyt version  : 0.2.6-dev
   notes       : development version
pafy version   : 0.3.74
Python version : 3.4.3 (default, May  1 2015, 19:14:18)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)]
Processor      : i386
Machine type   : x86_64
Architecture   : 64bit,
Platform       : Darwin-14.3.0-x86_64-i386-64bit
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /Users/ard/.config/mps-youtube
env:TERM       : screen-256color
env:SHELL      : /bin/zsh

 γ ~ uname -a
Darwin wasteland 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```
